title: "David Poplyonkin"
remote_theme: "mmistakes/minimal-mistakes@4.28.0"
copyright_url: "https://github.com/davidpoplyonkin/davidpoplyonkin.github.io/blob/main/LICENSE"

minimal_mistakes_skin: "dark"
atom_feed:
  hide: true

plugins:
- jekyll-remote-theme
- jekyll-include-cache
